title: Linux commands and Genomics data formats for biologists
description: PhD course about genomics format
url: "https://biocorecrg.github.io/PhD_course_genomics_format/"

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

sass:
  sass_dir: _sass
  style: compressed
